    name: Untame-TestPlugin
    main: pw.untamemadman.plugins.testplugin.TestPlugin
    version: 1.0
    author: untamemadman
    website: http://modding.untamemadman.pw
    commands:
      untamemadman:
         description: Shows information about me.
         usage: /untamemadman