    name: Untame-TestPlugin
    main: pw.untamemadman.plugins.testplugin.TestPlugin
    version: 2.0
    author: untamemadman
    website: http://modding.untamemadman.pw
    commands:
      untamemadman:
         description: The main command for the plugin.
         usage: /untamemadman <info/fire>
      untame:
         description: The main command for the plugin.
         usage: /untame <info/fire>