    name: Untame-TestPlugin
    main: pw.untamemadman.plugins.testplugin.TestPlugin
    version: 1.0
    author: untamemadman
    website: http://modding.untamemadman.pw


commands:
   untamemadman:
      description: This is a command
      usage: /untamemadman
      permission: Untame-TestPlugin.basic
      permission-message: You dont have <permission>