    name: Untame-TestPlugin
    main: pw.untamemadman.plugins.testplugin.TestPlugin
    version: 1.1
    author: untamemadman
    website: http://modding.untamemadman.pw
    commands:
      untamemadman:
         description: Shows information about me.
         usage: /untamemadman
      untame:
         description: Shows information about me.
         usage: /untame